name: NuGet Publish

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      package-version:
        description: 'Package version'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  nuget-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 3.1.101
        env: 
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      # Install dependencies
      - name: Install dependencies
        run: dotnet restore
    
      # Publish the package
      - name: Publish
        run: | # | character makes the "run" property multi-line, so we can put multiple commands in the same step
          mkdir __out
          dotnet pack -c Release -o __out --no-restore -p:PackageVersion=${{github.event.inputs.package-version}}
          dotnet nuget push "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_TOKEN}}
          rm -rf __out
